[
    {
        "content": "<p>I'm trying to reference a data type profile as part of a resource profile from within Forge.  The resource profile and the data type profiles are in different packages and I'm getting a \"The target resource is unavailable and cannot be validated\" message.  Is that because the profiles are in different packages within the same IG?</p>",
        "id": 153828167,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1463508046
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191320\">@Lloyd McKenzie</span> correct. Forge does an attempt to validate type references with respect to the base profile. However in order to do this, it needs access to the target StructureDefinition. If the target type is a core datatype or resource, or if the target profile is currently loaded in the application context, then Forge is able to resolve the associated StructureDefinition and validate the type reference. However if a type reference points to an external profile that is currently not loaded, then Forge cannot resolve the target StructureDefinition and will emit an information message to indicate that the unresolved type reference cannot be validated, i.e. validation status is undetermined.</p>",
        "id": 153828591,
        "sender_full_name": "Michel Rutten",
        "timestamp": 1463659478
    }
]