[
    {
        "content": "<p>In my profile (<a href=\"https://simplifier.net/bbmri.de/specimen\" target=\"_blank\" title=\"https://simplifier.net/bbmri.de/specimen\">https://simplifier.net/bbmri.de/specimen</a> under collection.bodySite.coding) I specified a ValueSet using its urn (got that from ART-DECOR).  Now the validator (in the IG publisher) throws an org.hl7.fhir.exceptions.FHIRException: not done yet: can't fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36 . So, is a ValueSet binding via urn valid? If yes, could this exception be downgraded to a warning so the IG Publisher can run and generate an IG? <br>\nThanks!</p>",
        "id": 175626932,
        "sender_full_name": "Noemi Deppenwiese",
        "timestamp": 1568383671
    },
    {
        "content": "<p>where does it blow up? what's the stack?</p>",
        "id": 175632568,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1568386990
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span>Exception in thread &quot;main&quot; java.lang.Error: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36\n        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:857)\n        at org.hl7.fhir.r5.context.SimpleWorkerContext.fetchResource(SimpleWorkerContext.java:565)\n        at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.resolveBinding(IGKnowledgeProvider.java:489)\n        at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.resolveBinding(IGKnowledgeProvider.java:424)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateDescription(ProfileUtilities.java:3021)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateDescription(ProfileUtilities.java:2930)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2649)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2711)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2711)\n        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateTable(ProfileUtilities.java:2504)\n        at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.snapshot(StructureDefinitionRenderer.java:350)\n        at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:5895)\n        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:5263)\n        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:3876)\n        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:735)\n        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:612)\n        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6451)\nCaused by: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36\n        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResourceWithException(BaseWorkerContext.java:800)\n        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:855)\n        ... 16 more\n</pre></div>",
        "id": 175791366,
        "sender_full_name": "Noemi Deppenwiese",
        "timestamp": 1568621060
    },
    {
        "content": "<p>you need to include the value set in the IG so that the publisher can find it. It's ok for it to have a urn:  but the error messag reflects that this is not normal behavior (we encourage use of http: urls but it's not mandatory)</p>",
        "id": 175796519,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1568625896
    },
    {
        "content": "<p>Did you get any feedback on this issue? Seems to be a problem with any unresolvable ValueSet binding. This also shows up in the official validator package when I try to validate this resource:<br>\n<a href=\"https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2\" target=\"_blank\" title=\"https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2\">https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2</a></p>",
        "id": 178466000,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571399450
    },
    {
        "content": "<p>A quick follow up on this. How do you make this work when you validate against a directory of Conformance resources? Should you include an XML file with the oid as the filename? Or define a Valuset with the oid as the ValueSet.url?</p>",
        "id": 178466204,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571399645
    },
    {
        "content": "<p>I made it work by using the ArtDecor URL for the ValueSet (\"valueSet\": \"<a href=\"http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623\" target=\"_blank\" title=\"http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623\">http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623</a>\") instead of just the URN in the profile... The publisher still complains about not finding a ValueSet there, but it continues the publishing process and and no longer throws an Exception. The output looks good enough and I dindn't encounter any further issues yet. <a href=\"/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png\" target=\"_blank\" title=\"publisher.png\">publisher.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png\" target=\"_blank\" title=\"publisher.png\"><img src=\"/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png\"></a></div><p>When validating resources (using just the urn as system), the validator only issues a warning and not an error which is good enough for our use case.</p>",
        "id": 178467059,
        "sender_full_name": "Noemi Deppenwiese",
        "timestamp": 1571400568
    },
    {
        "content": "<blockquote>\n<p>you need to include the value set in the IG so that the publisher can find it. It's ok for it to have a urn:  but the error messag reflects that this is not normal behavior (we encourage use of http: urls but it's not mandatory)</p>\n</blockquote>\n<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  Should the validator really stop the validation process when it can't locate a ValueSet definition? I think that is unwanted behaviour.</p>",
        "id": 178632140,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571643172
    },
    {
        "content": "<blockquote>\n<p>I made it work by using the ArtDecor URL for the ValueSet (\"valueSet\": \"<a href=\"http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623\" target=\"_blank\" title=\"http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623\">http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623</a>\") instead of just the URN in the profile... The publisher still complains about not finding a ValueSet there, but it continues the publishing process and and no longer throws an Exception. The output looks good enough and I dindn't encounter any further issues yet. <a href=\"/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png\" target=\"_blank\" title=\"publisher.png\">publisher.png</a></p>\n<p>When validating resources (using just the urn as system), the validator only issues a warning and not an error which is good enough for our use case.</p>\n</blockquote>\n<p>Thank you for the quick update <span class=\"user-mention\" data-user-id=\"221444\">@Noemi Deppenwiese</span> </p>\n<p>I can confirm this is working in my profiles as well. But I don't think this is the \"right\" solution. The spec is quite clear that a ValueSet binding using a oid value should be possible (urn:oid:, and in Norway we want to use this method for legacy ValueSets/CodeSystems that don't have any FHIR representation yet. The validator behaviour makes this more of an issue than necessary in my opinion.</p>",
        "id": 178642272,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571653210
    },
    {
        "content": "<p>ok, I'm home, and catching up. How are you invoking the validator? </p>\n<blockquote>\n<p>How do you make this work when you validate against a directory of Conformance resources? Should you include an XML file with the oid as the filename? Or define a Valuset with the oid as the ValueSet.url?</p>\n</blockquote>\n<p>The second. the filename doesn't matter - it will just load all the files it sees and see the value set. The fact that it's using a urn:oid: should be irrelevant, as long as you tell the validator to load it from somewhere</p>",
        "id": 178683576,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571682383
    },
    {
        "content": "<p>Thanks for your feedback.</p>\n<blockquote>\n<p>ok, I'm home, and catching up. How are you invoking the validator? </p>\n<p>The second. the filename doesn't matter - it will just load all the files it sees and see the value set. The fact that it's using a urn:oid: should be irrelevant, as long as you tell the validator to load it from somewhere</p>\n</blockquote>\n<p>I use command line like this:</p>\n<div class=\"codehilite\"><pre><span></span>java -jar /home/thomas/Downloads/org.hl7.fhir.validator.jar no-basis-Practitioner-example.xml -ig /media/sf_GitRepo/for-validation -version 4.0.0\n</pre></div>\n\n\n<p>the -ig value points at a catalog containing all my StructureDefinitions, also tried to indlude ValueSet/CodeSystem definition for the oid identified ValuSets/CodeSystems, but the validator still can't identify them and crashes with the \"not done yet: can't fetch urn:oid:xxx\" error message.</p>\n<p>It actually validates the SD's OK, but only until I try to validate the actual examples, then it seems to crash when resolving the ValueSet defined in the Profile.</p>\n<p>This is the profile in question:<br>\n<a href=\"https://simplifier.net/hl7norwayno-basis/nobasispractitioner\" target=\"_blank\" title=\"https://simplifier.net/hl7norwayno-basis/nobasispractitioner\">https://simplifier.net/hl7norwayno-basis/nobasispractitioner</a></p>\n<p>And the example: <br>\n<a href=\"https://simplifier.net/hl7norwayno-basis/practitioner-example\" target=\"_blank\" title=\"https://simplifier.net/hl7norwayno-basis/practitioner-example\">https://simplifier.net/hl7norwayno-basis/practitioner-example</a></p>\n<p>It only crashes on the last qualification part, because this is the only part where I remembered to add an actual binding of the value coding (have to fix that in the profile): <br>\n&lt;qualification&gt;<br>\n        &lt;code&gt;<br>\n            &lt;coding&gt;<br>\n                &lt;system value=\"urn:oid:2.16.578.1.12.4.1.1.7426\" /&gt;<br>\n                &lt;code value=\"152\" /&gt;<br>\n                &lt;display value=\"Ortopedisk kirurgi\" /&gt;<br>\n            &lt;/coding&gt;<br>\n        &lt;/code&gt;<br>\n    &lt;/qualification&gt;</p>",
        "id": 178730477,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571729990
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> <br>\nTurns out i did at least one mistake on my own. </p>\n<p>I used the same url value for my CodeSystem and ValueSet. When I introduced a ValueSet definition using the url: urn:oid:2.16.578.1.12.4.1.1.7426<br>\nAnd identified the CodeSystem using: urn:oid:2.16.578.1.12.4.1.1.7426.codesystem</p>\n<p>The validation still fails (my mock up CodeSystem does not actually define any codes yet) but the CodeSystem and ValueSet is resolved correctly by the validator, and the validator don't crash.</p>",
        "id": 178735782,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571734754
    },
    {
        "content": "<p>Oh good!</p>",
        "id": 178737473,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571736312
    },
    {
        "content": "<blockquote>\n<p>Oh good!</p>\n</blockquote>\n<p>Well, actually that did not fix it completely.</p>\n<p>I got this error that I expected, but the information bit turned out to be quite important:</p>\n<div class=\"codehilite\"><pre><span></span>*FAILURE* validating no-basis-Practitioner-example.xml:  error:1 warn:0 info:1\n  Error @ Practitioner.qualification[2].code.coding[0] (line 64, col12) : Unknown Code urn:oid:2.16.578.1.12.4.1.1.7426.codesystem#152 in urn:oid:2.16.578.1.12.4.1.1.7426.codesystem for &#39;urn:oid:2.16.578.1.12.4.1.1.7426.codesystem#152&#39;\n  Information @ Practitioner.qualification[2].code (line 63, col9) : This element does not match any known slice for the profile http://hl7.no/fhir/StructureDefinition/no-basis-Practitioner\n</pre></div>\n\n\n<p>The validator seems to find the CodeSystem where I now defined the code I am using. But It does not actually manage to find the ValueSet defined by urn:oid:xxx.</p>\n<p>The last change I made did  I did not  have a match for the slicing in the profile, because I did not remember to change the fixed string in the slice definition to match my new CodeSystem  url. When I fixed that one, the validator (again) tries to resolve the ValueSet binding in no-basis-Practitioner and crashes. The crash occurs even if I have defined the ValueSet in a file and put the file in the \"for-validation\" catalog just like the CodeSystem definition. (Now remembering to define different url's for the CodeSystem and the ValueSet).</p>\n<p>So there appears to be a problem when the validator tries to resolve ValueSet bindings identified by urn:oid:xxx</p>",
        "id": 178742218,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571740457
    },
    {
        "content": "<p>If I rename the valueset to something like this (like <span class=\"user-mention\" data-user-id=\"221444\">@Noemi Deppenwiese</span> did in her profiles) it all works out. The Validator finds both the ValueSet and the CodeSystem I have defined in the for-validation catalog, and validates the code defined in CodeSystem.</p>",
        "id": 178748381,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571745899
    },
    {
        "content": "<p>so I can't reproduce this - can you package up a folder containing all the relevant resources so I can make sure I have what you have to reproduce the problem?</p>",
        "id": 179000206,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1571952846
    },
    {
        "content": "<blockquote>\n<p>so I can't reproduce this - can you package up a folder containing all the relevant resources so I can make sure I have what you have to reproduce the problem?</p>\n</blockquote>\n<p>Shure, i will send you a link for download.</p>",
        "id": 179023500,
        "sender_full_name": "Thomas Tveit Rosenlund",
        "timestamp": 1571982011
    }
]