[
    {
        "content": "<p>Trying to get the validator to validate example instances against a given profile, and am getting an ArrayIndexOutOfBoundsException error.</p>\n<p>This occurs:</p>\n<ul>\n<li>with FHIR Validation tool Version 4.2.17-SNAPSHOT (current latest)</li>\n<li>using different examples in different IGs (tried with <a href=\"https://github.com/hl7au/au-fhir-base\" title=\"https://github.com/hl7au/au-fhir-base\">HL7 AU Base Implementation Guide</a> and <a href=\"https://github.com/HL7/bser\" title=\"https://github.com/HL7/bser\">HL7 Bidirection Services eReferrals FHIR IG</a>, and a local IG)</li>\n<li>only when the <code>-profile &lt;URL&gt;</code> switch is added to the command</li>\n</ul>\n<p>The command used (once either of the above IGs are cloned locally) - having randomly chosen an example and paired profile:</p>\n<div class=\"codehilite\"><pre><span></span>java -jar FHIR-validator/org.hl7.fhir.validator.jar -version 4.0.1 input/resources/condition/condition-BSeR-Diagnosis-eve-everywoman-diabetes.xml -ig http://hl7.org/fhir/us/bser -profile http://hl7.org/fhir/us/bser/StructureDefinition/BSeR-Diagnosis\n</pre></div>\n\n\n<p>with the output </p>\n<div class=\"codehilite\"><pre><span></span>FHIR Validation tool Version 4.2.17-SNAPSHOT (Git# 4bd0d60e5c1a). Built 2020-04-12T08:25:34.223+10:00 (3 days old)\nDetected Java version: 13.0.2 from /usr/lib/jvm/java-13-openjdk on amd64 (64bit). 3964MB available\nArguments: -version 4.0.1 input/resources/condition/condition-BSeR-Diagnosis-eve-everywoman-diabetes.xml -ig http://hl7.org/fhir/us/bser -profile http://hl7.org/fhir/us/bser/StructureDefinition/BSeR-Diagnosis\nDirectories: Current = /home/rob/pc_stuff/fhir/IGs/bser, Package Cache = /home/rob/.fhir/packages\nException in thread &quot;main&quot; java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7\n    at org.hl7.fhir.validation.cli.Params.loadCliContext(Params.java:97)\n    at org.hl7.fhir.validation.Validator.main(Validator.java:124)\n</pre></div>\n\n\n<p>The result is identical with the other IGs that I have tried. And without the <code>-profile</code> parameter, the run is clean with expected output.</p>\n<p>Having read the <a href=\"https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator\" title=\"https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator\">validator specs</a> and the command line help,  I think this is the correct invocation, but happy to be told otherwise.</p>\n<p>Any clues?</p>",
        "id": 194231623,
        "sender_full_name": "Rob Eastwood",
        "timestamp": 1586986941
    },
    {
        "content": "<p>I'm just trying the same thing now (it's been a little while) - trying to validate an instance with the IPS IG and our AllergyIntolerance profile with the latest validator (4.2.18), and I'm getting the same error <code>Exception in thread \"main\" java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7</code>.  <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>?</p>",
        "id": 194870444,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1587508553
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span></p>",
        "id": 194870532,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1587508604
    },
    {
        "content": "<p>Fix is here: <a href=\"https://github.com/hapifhir/org.hl7.fhir.core/pull/180\" title=\"https://github.com/hapifhir/org.hl7.fhir.core/pull/180\">https://github.com/hapifhir/org.hl7.fhir.core/pull/180</a></p>",
        "id": 194935352,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1587564292
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span> and <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> <br>\nCan I ask though - I see that the PR has been merged in, but does this need for me to wait for a new version of the Validator or does \"cloud magic\" happen?<br>\nI ask because re-running the command in the original post, I still get a failure, albeit slightly different:</p>\n<div class=\"codehilite\"><pre><span></span>java -jar org.hl7.fhir.validator.jar -version 4.0.1 input/resources/condition/condition-BSeR-Diagnosis-eve-everywoman-diabetes.xml -ig http://hl7.org/fhir/us/bser -profile http://hl7.org/fhir/us/bser/StructureDefinition/BSeR-Diagnosis\n\nFHIR Validation tool Version 4.2.18-SNAPSHOT (Git# 175d5fa0b72d). Built 2020-04-21T14:15:21.346+10:00 (48 hours old)\nDetected Java version: 1.8.0_191 from C:\\Program Files\\Java\\jre1.8.0_191 on amd64 (64bit). 3625MB available\nArguments: -version 4.0.1 input/resources/condition/condition-BSeR-Diagnosis-eve-everywoman-diabetes.xml -ig http://hl7.org/fhir/us/bser -profile http://hl7.org/fhir/us/bser/StructureDefinition/BSeR-Diagnosis\nDirectories: Current = C:\\work\\git\\bser, Package Cache = C:\\Users\\rob.eastwood\\.fhir\\packages\nException in thread &quot;main&quot; java.lang.ArrayIndexOutOfBoundsException: 7\n        at org.hl7.fhir.validation.cli.Params.loadCliContext(Params.java:97)\n        at org.hl7.fhir.validation.Validator.main(Validator.java:124)\n</pre></div>\n\n\n<p>Maybe there is something I need to do my end?</p>",
        "id": 195018992,
        "sender_full_name": "Rob Eastwood",
        "timestamp": 1587618103
    },
    {
        "content": "<p>I haven't done a release yet</p>",
        "id": 195019231,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1587618485
    },
    {
        "content": "<p>gotcha - sorry for the noise!</p>",
        "id": 195019235,
        "sender_full_name": "Rob Eastwood",
        "timestamp": 1587618517
    },
    {
        "content": "<p>Thank you very much <span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span> and <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> - I can confirm that is now fixed</p>",
        "id": 195128164,
        "sender_full_name": "Rob Eastwood",
        "timestamp": 1587681536
    }
]