[
    {
        "content": "<p>I'm getting terminology server timeouts when trying to do a run.  These have been happening randomly all day yesterday and today.  Today's are interesting because the error is different and the spot in the build is different:</p>\n<div class=\"codehilite\"><pre><span></span><code>Validating Conformance Resources                                                 (01:18.0360)\nPublishing Content Failed: An error occurred trying to process this transaction request (02:01.0683)\n                                                                                 (02:01.0684)\nUse -? to get command line help                                                  (02:01.0685)\n                                                                                 (02:01.0685)\nStack Dump (for debugging):                                                      (02:01.0685)\norg.hl7.fhir.r5.utils.client.EFhirClientException: An error occurred trying to process this transaction request\n    at org.hl7.fhir.r5.utils.client.FHIRToolingClient.handleException(FHIRToolingClient.java:325)\n    at org.hl7.fhir.r5.utils.client.FHIRToolingClient.transaction(FHIRToolingClient.java:296)\n    at org.hl7.fhir.convertors.txClient.TerminologyClientR5.validateBatch(TerminologyClientR5.java:120)\n    at org.hl7.fhir.r5.context.BaseWorkerContext.validateCodeBatch(BaseWorkerContext.java:820)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetInclude(ValueSetValidator.java:121)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetCompose(ValueSetValidator.java:68)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSet(ValueSetValidator.java:58)\n    at org.hl7.fhir.validation.instance.InstanceValidator.checkSpecials(InstanceValidator.java:3919)\n    at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3891)\n    at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3750)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4916)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:700)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:675)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:4867)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:3843)\n    at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3824)\n    at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:874)\n    at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:729)\n    at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8414)\nCaused by: java.net.SocketTimeoutException: timeout\n    at okio.Okio$4.newTimeoutException(Okio.java:230)\n    at okio.AsyncTimeout.exit(AsyncTimeout.java:285)\n    at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)\n    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)\n    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)\n    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)\n    at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)\n    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n    at org.hl7.fhir.r5.utils.client.network.RetryInterceptor.intercept(RetryInterceptor.java:60)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)\n    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)\n    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)\n    at okhttp3.RealCall.execute(RealCall.java:69)\n    at org.hl7.fhir.r5.utils.client.network.FhirRequestBuilder.executeAsBatch(FhirRequestBuilder.java:214)\n    at org.hl7.fhir.r5.utils.client.network.Client.executeBundleRequest(Client.java:197)\n    at org.hl7.fhir.r5.utils.client.network.Client.postBatchRequest(Client.java:181)\n    at org.hl7.fhir.r5.utils.client.FHIRToolingClient.transaction(FHIRToolingClient.java:294)\n    ... 17 more\nCaused by: java.net.SocketTimeoutException: Read timed out\n    at java.base/java.net.SocketInputStream.socketRead0(Native Method)\n    at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)\n    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)\n    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)\n    at okio.Okio$2.read(Okio.java:139)\n    at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n    ... 43 more\n</code></pre></div>",
        "id": 219260815,
        "sender_full_name": "Jean Duteau",
        "timestamp": 1607460641
    },
    {
        "content": "<p>After testing a different IG of mine which ran fine to completion, I deleted my txcache and reran the publisher.  I still get an error at the same place, but it is a slightly different error:</p>\n<div class=\"codehilite\"><pre><span></span><code>Validating Conformance Resources                                                 (01:11.0885)\nPublishing Content Failed: null                                                  (01:22.0606)\n                                                                                 (01:22.0606)\nUse -? to get command line help                                                  (01:22.0607)\n                                                                                 (01:22.0607)\nStack Dump (for debugging):                                                      (01:22.0608)\njava.lang.NullPointerException\n    at org.hl7.fhir.r5.context.BaseWorkerContext.processValidationResult(BaseWorkerContext.java:1057)\n    at org.hl7.fhir.r5.context.BaseWorkerContext.validateCodeBatch(BaseWorkerContext.java:825)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetInclude(ValueSetValidator.java:121)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetCompose(ValueSetValidator.java:68)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSet(ValueSetValidator.java:58)\n    at org.hl7.fhir.validation.instance.InstanceValidator.checkSpecials(InstanceValidator.java:3919)\n    at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3891)\n    at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3750)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4916)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:700)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:675)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:4867)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:3843)\n    at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3824)\n    at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:874)\n    at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:729)\n    at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8414)\n</code></pre></div>",
        "id": 219263117,
        "sender_full_name": "Jean Duteau",
        "timestamp": 1607461864
    },
    {
        "content": "<p>ok I just talked to James and Mark (tooling tech team) and we're going to put nginx in front of the terminology server to see if that makes any difference, but it won't be this week</p>",
        "id": 219264504,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1607462572
    },
    {
        "content": "<p>i'm just wondering if this new error is a timeout?  it's a NPE when validating a value set</p>",
        "id": 219264757,
        "sender_full_name": "Jean Duteau",
        "timestamp": 1607462705
    },
    {
        "content": "<p>looking at the code, this does actually seem not to be a timeout.  it appears that it's getting an answer back from the tx server but it's not in the format that the code is expecting?</p>",
        "id": 219265492,
        "sender_full_name": "Jean Duteau",
        "timestamp": 1607463056
    },
    {
        "content": "<p>no that's something else. will be fixed next release. I'm surprised it hasn't happened before, actually.</p>",
        "id": 219269897,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1607465316
    },
    {
        "content": "<p>I am intermittently getting this error as well, but only on some IGs. Was this fix implemented? Is it a function of the number/size of value sets?</p>",
        "id": 222655059,
        "sender_full_name": "Bryn Rhodes",
        "timestamp": 1610576485
    },
    {
        "content": "<p>Getting Tx server timeout 'Error fetching the server's capability statement: connection timed out'. Cleared my Tx cache but no luck. <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span></p>",
        "id": 229514731,
        "sender_full_name": "David deRoode",
        "timestamp": 1615310117
    }
]