[
    {
        "content": "<p>Getting an error that I don't think is a problem with my IG:</p>\n<p>org.hl7.fhir.exceptions.FHIRException: Unable to resolve package id hl7.fhir.pubpack#0.0.6<br>\n    at org.hl7.fhir.utilities.cache.FilesystemPackageCacheManager.fetchTheOldWay(FilesystemPackageCacheManager.java:651)<br>\n    at org.hl7.fhir.utilities.cache.FilesystemPackageCacheManager.loadFromPackageServer(FilesystemPackageCacheManager.java:220)<br>\n    at org.hl7.fhir.utilities.cache.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:473)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.loadPubPack(Publisher.java:2257)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:1765)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:1365)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:702)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7815)</p>",
        "id": 203919090,
        "sender_full_name": "Sarah Gaunt",
        "timestamp": 1594792329
    },
    {
        "content": "<p>And had to add the following because it made me laugh!</p>\n<p>2020-07-15 05:52:19.623 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:75] Failed to resolve package hl7.fhir.pubpack#0.0.6 from server: <a href=\"http://packages.fhir.org\">http://packages.fhir.org</a><br>\n2020-07-15 05:54:31.340 [main] INFO  o.h.f.u.c.BasePackageCacheManager [BasePackageCacheManager.java:75] Failed to resolve package hl7.fhir.pubpack#0.0.6 from server: <a href=\"http://packages2.fhir.org/packages\">http://packages2.fhir.org/packages</a></p>",
        "id": 203919369,
        "sender_full_name": "Sarah Gaunt",
        "timestamp": 1594792703
    },
    {
        "content": "<p>Experiencing the same issue with the CarinBB IG.</p>",
        "id": 203989189,
        "sender_full_name": "Saul Kravitz",
        "timestamp": 1594835430
    },
    {
        "content": "<p>Experiencing the same issue</p>",
        "id": 203998070,
        "sender_full_name": "Natasha Singh",
        "timestamp": 1594839621
    },
    {
        "content": "<p>So am I, with several IGs. Tried version 1.1.0 and 1.1.3</p>",
        "id": 203998862,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1594839984
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span></p>",
        "id": 203999051,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1594840083
    },
    {
        "content": "<p>Also seeing this issue</p>",
        "id": 204020799,
        "sender_full_name": "Silvio Luthi",
        "timestamp": 1594852078
    },
    {
        "content": "<p>apologies. A problem on the server and I fixed the wrong server. I've added more defense and survelliance of the server into my infrastructure</p>",
        "id": 204035840,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1594864241
    },
    {
        "content": "<p>.. the right server, that is</p>",
        "id": 204035873,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1594864291
    },
    {
        "content": "<p>I can confirm this has been fixed/resolved. Just successfully published one of the IGs that was failing yesterday. Thanks <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> !</p>",
        "id": 204103596,
        "sender_full_name": "Sean McIlvenna",
        "timestamp": 1594914860
    },
    {
        "content": "<p>Seeing this error again, is there another issue with the publisher? <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span></p>",
        "id": 204699118,
        "sender_full_name": "Silvio Luthi",
        "timestamp": 1595440095
    },
    {
        "content": "<p>I'm seeing it too:<br>\nFailed to resolve package hl7.fhir.pubpack#0.0.6 from server: <a href=\"http://packages.fhir.org\">http://packages.fhir.org</a></p>",
        "id": 204702593,
        "sender_full_name": "Rick Geimer",
        "timestamp": 1595441784
    },
    {
        "content": "<p>is it resolved now?</p>",
        "id": 204715283,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1595448118
    },
    {
        "content": "<p>ill attempt a deploy to check</p>",
        "id": 204715723,
        "sender_full_name": "Silvio Luthi",
        "timestamp": 1595448332
    },
    {
        "content": "<p>Still seeing this</p>",
        "id": 204715967,
        "sender_full_name": "Silvio Luthi",
        "timestamp": 1595448455
    },
    {
        "content": "<p>just got failure</p>",
        "id": 204717313,
        "sender_full_name": "John Moehrke",
        "timestamp": 1595449065
    },
    {
        "content": "<p>ok I think I have solved this now</p>",
        "id": 204721405,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1595451127
    },
    {
        "content": "<p>Yes, it works now. Thanks.</p>",
        "id": 204724582,
        "sender_full_name": "Yan Heras",
        "timestamp": 1595452973
    },
    {
        "content": "<p>Yes, this looks resolved, thank you</p>",
        "id": 204729738,
        "sender_full_name": "Silvio Luthi",
        "timestamp": 1595456704
    }
]