[
    {
        "content": "<p>Hi, wondering if anyone might know why <a href=\"https://github.com/HL7/fhir-outcome-criteria-framework-ig\">https://github.com/HL7/fhir-outcome-criteria-framework-ig</a> isn't building.</p>",
        "id": 210328461,
        "sender_full_name": "Bob Dolin",
        "timestamp": 1600295658
    },
    {
        "content": "<p>It builds locally, with this version: FHIR IG Publisher Version 1.1.6, but from the github build, I get this:</p>\n<p>onGenerate:<br>\nException in thread \"main\" java.lang.Error: Error generating build: the file /scratch/ig-build-temp-CVWGEO/repo/temp/pages/_includes/StructureMap-depressionMeasure-summary.xhtml is being generated more than once (may differ by case)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.checkMakeFile(Publisher.java:2950)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.fragment(Publisher.java:7825)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsCanonical(Publisher.java:7681)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6632)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6564)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4849)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:871)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:717)<br>\n    at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8276)</p>",
        "id": 210328516,
        "sender_full_name": "Bob Dolin",
        "timestamp": 1600295708
    },
    {
        "content": "<p>Sounds like you've got a case issue somewhere (Windows doesn't care, Unix does).  Look inside the artifact and ensure that the filename, the id and the canonical URL have the same case.  If the artifact is explicitly referenced in the IG, check the case there too.</p>",
        "id": 210328683,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1600295845
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191320\">@Lloyd McKenzie</span> I checked and double checked and don't see any case issues. There was an incorrect reference which I fixed, but still getting same error.</p>",
        "id": 210330186,
        "sender_full_name": "Bob Dolin",
        "timestamp": 1600297125
    },
    {
        "content": "<p>I do have a Library and a Measure both named 'depressionMeasure', but I thought that was ok</p>",
        "id": 210330410,
        "sender_full_name": "Bob Dolin",
        "timestamp": 1600297288
    },
    {
        "content": "<p>bug in the publisher- sorry. Will be fixed in next release</p>",
        "id": 210331718,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1600298338
    },
    {
        "content": "<p>sometime in the next 24 hours</p>",
        "id": 210331728,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1600298348
    },
    {
        "content": "<p>Thanks <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span></p>",
        "id": 210332234,
        "sender_full_name": "Bob Dolin",
        "timestamp": 1600298830
    }
]