[
    {
        "content": "<p>I'm getting many warnings stating that the SNOMED codes I'm using are not valid in <a href=\"http://snomed.info/sct\">http://snomed.info/sct</a>.  I know that the codes are valid.  How do I fix the warning?  The IG is the Vital Signs IG <a href=\"http://build.fhir.org/ig/HL7/cimi-vital-signs/branches/master/index.html\">http://build.fhir.org/ig/HL7/cimi-vital-signs/branches/master/index.html</a>      The qa output can be found at  <a href=\"http://build.fhir.org/ig/HL7/cimi-vital-signs/branches/master/qa.html\">http://build.fhir.org/ig/HL7/cimi-vital-signs/branches/master/qa.html</a></p>",
        "id": 206198768,
        "sender_full_name": "Nathan Davis",
        "timestamp": 1596749037
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span></p>",
        "id": 206201230,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1596750576
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191411\">@Nathan Davis</span> the only warning I get is this one:</p>\n<blockquote>\n<p>The code 24311000205101 is not valid in the system <a href=\"http://snomed.info/sct\">http://snomed.info/sct</a></p>\n</blockquote>\n<p>This looks correct to me: I don't find 24311000205101 in the snomed browser</p>",
        "id": 206209334,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1596756303
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> Thank you!</p>",
        "id": 206258942,
        "sender_full_name": "Nathan Davis",
        "timestamp": 1596808415
    },
    {
        "content": "<p>I an dead in the water here with publisher 1.1.9 now - was working same content with 1.1.5 - when it checks for supported code systems set it crashes:   Terminology server: Check for supported code systems for <a href=\"http://snomed.info/sct\">http://snomed.info/sct</a>  (02:30.0230)<br>\nPublishing Content Failed: null                                                  (02:41.0454)<br>\n    Was there a change and I have to put the cache file somewhere else, or declare something?   <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>   what changed and how can I get the UTG build working again now?</p>",
        "id": 206260940,
        "sender_full_name": "Ted Klein",
        "timestamp": 1596809361
    },
    {
        "content": "<p>I'm getting the same error with 1.1.9:</p>\n<div class=\"codehilite\"><pre><span></span><code>Terminology server: Check for supported code systems for http://snomed.info/sct  (02:42.0231)\nPublishing Content Failed: null                                                  (02:55.0128)\n                                                                                 (02:55.0129)\nUse -? to get command line help                                                  (02:55.0129)\n                                                                                 (02:55.0130)\nStack Dump (for debugging):                                                      (02:55.0130)\njava.lang.NullPointerException\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetIncludeConcept(ValueSetValidator.java:149)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetInclude(ValueSetValidator.java:106)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSetCompose(ValueSetValidator.java:65)\n    at org.hl7.fhir.validation.instance.type.ValueSetValidator.validateValueSet(ValueSetValidator.java:55)\n    at org.hl7.fhir.validation.instance.InstanceValidator.checkSpecials(InstanceValidator.java:3647)\n    at org.hl7.fhir.validation.instance.InstanceValidator.startInner(InstanceValidator.java:3619)\n    at org.hl7.fhir.validation.instance.InstanceValidator.start(InstanceValidator.java:3497)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validateResource(InstanceValidator.java:4595)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:685)\n    at org.hl7.fhir.validation.instance.InstanceValidator.validate(InstanceValidator.java:661)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:4722)\n    at org.hl7.fhir.igtools.publisher.Publisher.validate(Publisher.java:3720)\n    at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3701)\n    at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:854)\n    at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:715)\n    at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7912)\n</code></pre></div>",
        "id": 206265810,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1596811667
    },
    {
        "content": "<p>Apparently it's a bug in the ValueSetValidator code.  I think I see where the NPE is happening.</p>",
        "id": 206267260,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1596812367
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191982\">@Ted Klein</span> It looks like that problem has been fixed in 1.1.10.</p>",
        "id": 206269016,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1596813158
    },
    {
        "content": "<p>OK let me install that one.   Grahame told me early this morning I should be using 1.1.9</p>",
        "id": 206291810,
        "sender_full_name": "Ted Klein",
        "timestamp": 1596824209
    }
]