[
    {
        "content": "<p>Consider a Task with restriction.period set.</p>\n<p>I was reading through the Task State Machine documentation (<a href=\"https://www.hl7.org/fhir/task.html#statemachine\">https://www.hl7.org/fhir/task.html#statemachine</a>) and was wondering, if a Task is in progress and a user doesn't complete the Task in the specified period, it looks like the Task should transition to the \"failed\" state. In the documentation for Task statuses (<a href=\"https://www.hl7.org/fhir/valueset-task-status.html\">https://www.hl7.org/fhir/valueset-task-status.html</a>), it defines failed to mean \"The task was attempted but could not be completed due to some error\". I am hung up on \"..due to some error\". Would not completing it in the specified period, not because of error but because the owner just wasn't able to complete the Task in time, counts as an error or is an error here meant more as a system error?</p>\n<p>I realize this Task State Machine is a \"typical\" example, but I'm curious if the desired behaviour in my example is to transition the Task to a failed state or if \"error\" here means something stricter than how I am interpreting it.</p>",
        "id": 263386506,
        "sender_full_name": "Kyle Thompson",
        "timestamp": 1638412499
    },
    {
        "content": "<p>I think we've got a change request that refines that description somewhat in R5.  \"Some error\" might better be framed as \"some problem\".  It could be system, user, environment or anything else.  The real world intervened in a way that means \"this isn't going to get finished\".</p>",
        "id": 263387952,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1638414209
    },
    {
        "content": "<p>So \"didn't do it in the necessary time, so it's either not going to happen, or if it does, it won't matter/count\" would definitely fall into the \"failed\" bucket.</p>",
        "id": 263387971,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1638414242
    },
    {
        "content": "<p>OK, rephrasing \"some error\" to \"some problem\" makes sense. Thanks!</p>",
        "id": 263444461,
        "sender_full_name": "Kyle Thompson",
        "timestamp": 1638455281
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"401577\">Kyle Thompson</span> has marked this topic as resolved.</p>",
        "id": 263444642,
        "sender_full_name": "Notification Bot",
        "timestamp": 1638455346
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"401577\">Kyle Thompson</span> has marked this topic as resolved.</p>",
        "id": 263444656,
        "sender_full_name": "Notification Bot",
        "timestamp": 1638455349
    }
]