[
    {
        "content": "<p>I am using the validator(5.0.7) to validate a folder of FHIR profiles as part of our build pipeline. Success of the build depends on the exit code of the validator.  </p>\n<p>Validation errors set the exit code to !=0 what means an error this also shows in the output of the validator. This is ok as an error was found and our build fails.<br>\nBut during validation the validator tries to make snapshots ( I do not use the -snapshot argument). The creation of these snapshots fails in this case due to \"is not a valid constraint on the base\". But after this failure the validator continues and validation of the same profile succeeds without any error, warning or info. </p>\n<p>1)Should the exit code of the validator not indicates an error after snapshot generation fails during validation? Meaning being set to anything !=0.<br>\n2)It is strange to me that validation of a profile can succeed even when the snapshot generation for the same profile during the validation fails.</p>\n<p>I see the same behavior of the validator for R4 and STU3</p>",
        "id": 202682210,
        "sender_full_name": "Hans van Amstel",
        "timestamp": 1593693866
    },
    {
        "content": "<p>hmm. the trouble is that I may not know whether the snapshot that failed is critical for the outcome.</p>",
        "id": 202687166,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1593696247
    },
    {
        "content": "<p>can you give me a nice precise set up that I can add as a test case that reproduces your scenario?</p>",
        "id": 202687331,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1593696315
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  I have send the profiles and the commands used via mail. It will have the same result as shown below.</p>\n<div class=\"codehilite\"><pre><span></span><code>Detected Java version: 13.0.1 from /usr/java/openjdk-13 on amd64 (64bit). 4012MB available\nArguments: SkinQuestionnaireResponse.structuredefinition.xml -version 3.0 -ig /usr/data/npmpackage/package -ig hl7.fhir.uv.sdc#2.0.0 -recurse\nDirectories: Current = /usr/data/npmpackage/package, Package Cache = /home/tfsagent/.fhir/packages\n .. FHIR Version 3.0, definitions from hl7.fhir.r3.core#3.0.2\n .. connect to tx server @ http://tx.fhir.org\n (v3.0.2)\n+ .. load IG from /usr/data/npmpackage/package\n+ .. load IG from hl7.fhir.uv.sdc#2.0.0\n .. validate [SkinQuestionnaireResponse.structuredefinition.xml]\nUnable to generate snapshot for SkinQuestionnaireResponse from ILS-QuestionnaireResponse because Profile SkinQuestionnaireResponse (https://www.fhir.philips.com/3.0/StructureDefinition/personalHealth/skin/skinIssueQuestionnaire-v1/SkinQuestionnaireResponse), element QuestionnaireResponse.questionnaire. Error generating snapshot: The target profile https://www.fhir.philips.com/3.0/StructureDefinition/common/resource/general/questionnaireResponse-v1/ILS-QuestionnaireResponse is not a valid constraint on the base ([CanonicalType[http://hl7.org/fhir/StructureDefinition/Questionnaire]]) at QuestionnaireResponse.questionnaire\norg.hl7.fhir.exceptions.DefinitionException: Profile SkinQuestionnaireResponse (https://www.fhir.philips.com/3.0/StructureDefinition/personalHealth/skin/skinIssueQuestionnaire-v1/SkinQuestionnaireResponse), element QuestionnaireResponse.questionnaire. Error generating snapshot: The target profile https://www.fhir.philips.com/3.0/StructureDefinition/common/resource/general/questionnaireResponse-v1/ILS-QuestionnaireResponse is not a valid constraint on the base ([CanonicalType[http://hl7.org/fhir/StructureDefinition/Questionnaire]]) at QuestionnaireResponse.questionnaire\n    at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:675)\n    at org.hl7.fhir.r5.context.SimpleWorkerContext.generateSnapshot(SimpleWorkerContext.java:646)\n    at org.hl7.fhir.r5.context.SimpleWorkerContext.allStructures(SimpleWorkerContext.java:529)\n    at org.hl7.fhir.validation.ValidationEngine.prepare(ValidationEngine.java:1315)\n    at org.hl7.fhir.validation.cli.services.ValidationService.validateSources(ValidationService.java:53)\n    at org.hl7.fhir.validation.Validator.main(Validator.java:202)\nSuccess...validating SkinQuestionnaireResponse.structuredefinition.xml: error:0 warn:0 info:0```\n</code></pre></div>",
        "id": 202708371,
        "sender_full_name": "Hans van Amstel",
        "timestamp": 1593705695
    },
    {
        "content": "<p>yes I thought this one wouldn't be easy to fix. The <code>unable to generate...</code> message is not germane to the outcome of the validation, so it doesn't feature in the exit code</p>",
        "id": 202757464,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1593734692
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  Thanks for looking into it. Is this something that will be fixed so that I get an error exit code. Or maybe add an additional strictness argument for setting  a strictness level that when set to the max will have all these generation errors and the warnings set an error exit code.</p>",
        "id": 202782141,
        "sender_full_name": "Hans van Amstel",
        "timestamp": 1593767001
    },
    {
        "content": "<p>well, I worked more on validation of profiles (as opposed to validation by profiles) and you'll get both an error and a exit code from the next release</p>",
        "id": 202784968,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1593769038
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  Thanks a lot. Looking forward to integrating and using it.</p>",
        "id": 202785163,
        "sender_full_name": "Hans van Amstel",
        "timestamp": 1593769199
    }
]