[
    {
        "content": "<p>Hello,<br>\nI am getting the following internal error, whenever I am executing the following query on the HAPI server \"<a href=\"http://fhirtest.uhn.ca/baseDstu3/Encounter?patient=330828&amp;date=ge2017-01-01&amp;_include:recurse=Encounter:practitioner&amp;_lastUpdated=ge2017-11-10\" target=\"_blank\" title=\"http://fhirtest.uhn.ca/baseDstu3/Encounter?patient=330828&amp;date=ge2017-01-01&amp;_include:recurse=Encounter:practitioner&amp;_lastUpdated=ge2017-11-10\">http://fhirtest.uhn.ca/baseDstu3/Encounter?patient=330828&amp;date=ge2017-01-01&amp;_include:recurse=Encounter:practitioner&amp;_lastUpdated=ge2017-11-10</a>\" </p>\n<p><a href=\"/user_uploads/10155/YxUrkUuzjRZvyCPTI0de1sCR/pasted_image.png\" target=\"_blank\" title=\"pasted_image.png\">pasted image</a> <br>\nThe strange thing is, whenever I omit the _lastUpdated parameter, this search query executes properly. Is it an issue on the HAPI server?</p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/YxUrkUuzjRZvyCPTI0de1sCR/pasted_image.png\" target=\"_blank\" title=\"pasted image\"><img src=\"/user_uploads/10155/YxUrkUuzjRZvyCPTI0de1sCR/pasted_image.png\"></a></div>",
        "id": 153920560,
        "sender_full_name": "Dimitar",
        "timestamp": 1511256555
    },
    {
        "content": "<p>Can a _lastUpdated parameter, not be used together with a recurse include or revInclude?</p>",
        "id": 153920568,
        "sender_full_name": "Dimitar",
        "timestamp": 1511257159
    },
    {
        "content": "<p>it can't, but it doesn't apply to the included stuff</p>",
        "id": 153920571,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1511257317
    },
    {
        "content": "<p>What is the meaning of the error in that case?</p>",
        "id": 153920575,
        "sender_full_name": "Dimitar",
        "timestamp": 1511257586
    },
    {
        "content": "<p>don't know - maybe ask on the HAPI email list?</p>",
        "id": 153920576,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1511257633
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  alright, will do. But technically, this query should execute, right?</p>",
        "id": 153920577,
        "sender_full_name": "Dimitar",
        "timestamp": 1511257671
    },
    {
        "content": "<p>y</p>",
        "id": 153920578,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1511257703
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"194501\">@Dimitar</span> , this was a bug on the server. It has been fixed, and the fix is in the current 3.2.0 SNAPSHOT build. :)</p>",
        "id": 153921525,
        "sender_full_name": "James Agnew",
        "timestamp": 1511548339
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191319\">@James Agnew</span>  Great! Glad I could help :), if I did anyways. I implemented a workaround, just in case, I get it elsewhere, removing the  _lastUpdated search parameter, from the search params, if I catch an error like that. What was the problem with it anyways?</p>",
        "id": 153921560,
        "sender_full_name": "Dimitar",
        "timestamp": 1511567594
    },
    {
        "content": "<p>Essentially it was a bug with the _include handling. Oddly enough it was more to do with the recursive _include where the second round of including failed if _lastUpdate left it with nothing to include. Blah!</p>",
        "id": 153921564,
        "sender_full_name": "James Agnew",
        "timestamp": 1511577431
    }
]