[
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191381\">@Jason Walonoski</span> a synthea question: I've followed the installation instructions, and gotten the following error:</p>",
        "id": 153915804,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508885567
    },
    {
        "content": "<p>Could not find activemodel-4.2.8 in any of the sources</p>",
        "id": 153915805,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508885575
    },
    {
        "content": "<p>gem install active model installed 5.1.4...</p>",
        "id": 153915806,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508885590
    },
    {
        "content": "<p>I set it up and used it just in the past few days in preparing for the IHIC Datathon.  I don't recall getting that particular error, so I'm not sure what to say about that at the moment.  I created about 5000 patients for the backup server in the cloud that we used.</p>",
        "id": 153915807,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1508885736
    },
    {
        "content": "<p>I can't figure out how to run it on the current version of ruby. .. trying an older version</p>",
        "id": 153915808,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508885798
    },
    {
        "content": "<p>I think the output is meant to be R3 not R2, but the cardinalities are thoroughly mixed up</p>",
        "id": 153915830,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508891919
    },
    {
        "content": "<p>btw, I gave up trying to get it run - dependency mess and I don't know Ruby at all to hack my through the thicket, and Rob sent me some generated data</p>",
        "id": 153915832,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508892120
    },
    {
        "content": "<p>I guess <span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span> gave up on getting Synthea to work, but for others looking at this thread, it should work with any version of Ruby &gt;= 2.1. We've tested it on Mac OS X, Windows, and Linux.</p>",
        "id": 153916010,
        "sender_full_name": "Jason Walonoski",
        "timestamp": 1508940502
    },
    {
        "content": "<p>The <code>fhir</code> output is meant to be STU3 and the <code>fhir_dstu2</code> output is meant to be DSTU2. If you find cardinality issues I'd appreciate bug reports.</p>",
        "id": 153916011,
        "sender_full_name": "Jason Walonoski",
        "timestamp": 1508940556
    },
    {
        "content": "<p>In the coming months, we'll be migrating from Ruby to Java for performance reasons. Hopefully that will make it easier for the broader community to use and contribute to.</p>",
        "id": 153916012,
        "sender_full_name": "Jason Walonoski",
        "timestamp": 1508940609
    },
    {
        "content": "<p>Procedure.reasonReference,  Encounter.reason, Organization.type</p>",
        "id": 153916063,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508960950
    },
    {
        "content": "<p>it will not work ]with ruby 2.4 - a version specific dependency won't work with ruby 2.4</p>",
        "id": 153916064,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508961011
    },
    {
        "content": "<p>and I gave up trying to sort out internal dependencies some where down the ruby tree</p>",
        "id": 153916065,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508961053
    },
    {
        "content": "<p>wasn't impressed that I couldn't do the install with my old ruby and couldn't upgrade it, but that's nothingto do with you</p>",
        "id": 153916066,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1508961080
    },
    {
        "content": "<p>I had significant permissions issues with the Ubuntu .deb package version of ruby, so I removed that and used RVM instead to install ruby, which worked fine.  I'm using ruby 2.4.1p111 on Ubuntu 16.04.3.  Doing a spot check on the STU3 output, I see the cardinality issue on Procedure.reasonReference and Encounter.reason, but Organization.type appears correct.  I've added an issue for it (#239) on the Synthea GitHub.</p>",
        "id": 153916244,
        "sender_full_name": "Rob Hausam",
        "timestamp": 1509000949
    },
    {
        "content": "<p>Thanks for the bug reports here and on github.</p>",
        "id": 153916568,
        "sender_full_name": "Jason Walonoski",
        "timestamp": 1509148526
    },
    {
        "content": "<p>These issues (and a few others I found) are fixed in <code>master</code>.... Will be rolled into the next release.</p>",
        "id": 153916987,
        "sender_full_name": "Jason Walonoski",
        "timestamp": 1509478562
    }
]