[
    {
        "content": "<p>Hi,</p>\n<p>why <a href=\"http://fhirsandbox.kanta.fi\" target=\"_blank\" title=\"http://fhirsandbox.kanta.fi\">http://fhirsandbox.kanta.fi</a> is empty and create resources fails?</p>\n<p>SOLVED - There was a confusion about how sandbox shows resources and search function not returning CodeSystems like our own HAPI server.</p>",
        "id": 153913011,
        "sender_full_name": "Hannu Korhonen",
        "timestamp": 1507532683
    },
    {
        "content": "<p>@</p>",
        "id": 153913098,
        "sender_full_name": "Mika Tuomainen",
        "timestamp": 1507551664
    },
    {
        "content": "<p>Terve, is authorization sandbox down or have there been some changes in accessing it? <a href=\"https://fhirsandbox2.kanta.fi/openid-connect-kela/registeruser\" target=\"_blank\" title=\"https://fhirsandbox2.kanta.fi/openid-connect-kela/registeruser\">https://fhirsandbox2.kanta.fi/openid-connect-kela/registeruser</a> returns ERR_CONNECTION_RESET (Chrome)</p>",
        "id": 153917039,
        "sender_full_name": "Jukka Pirinen",
        "timestamp": 1509515754
    },
    {
        "content": "<p>The address has changed to <a href=\"https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/\" target=\"_blank\" title=\"https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/\">https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/</a>  <br>\nThis page has all the relevant addresses etc: <a href=\"http://www.kanta.fi/en/web/ammattilaisille/tarkeaa-tietoa-kehittajille\" target=\"_blank\" title=\"http://www.kanta.fi/en/web/ammattilaisille/tarkeaa-tietoa-kehittajille\">http://www.kanta.fi/en/web/ammattilaisille/tarkeaa-tietoa-kehittajille</a></p>",
        "id": 153917788,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1509977209
    },
    {
        "content": "<p>Warning!<br>\nFailed to load capability statement, error was: ca.uhn.fhir.rest.server.exceptions.InternalErrorException: HTTP 500 Internal Server Error</p>\n<p>problems in sandbox environment?</p>",
        "id": 153918432,
        "sender_full_name": "Hannu Korhonen",
        "timestamp": 1510213985
    },
    {
        "content": "<p>Not problems, but scheduled update to fix some findings from last week. Everything should be up and running right now!</p>\n<p>The updates are announced here: <a href=\"http://www.kanta.fi/fi/web/ammattilaisille/omakannan-omatietovaranto\" target=\"_blank\" title=\"http://www.kanta.fi/fi/web/ammattilaisille/omakannan-omatietovaranto\">http://www.kanta.fi/fi/web/ammattilaisille/omakannan-omatietovaranto</a></p>",
        "id": 153918442,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1510220221
    },
    {
        "content": "<p>The  server <a href=\"http://fhirsandbox2-auth.kanta.fi\" target=\"_blank\" title=\"http://fhirsandbox2-auth.kanta.fi\">fhirsandbox2-auth.kanta.fi</a> does not seem to return OAuth refresh token. We are able to get only the access_token, whose TTL is one hour. Is this a bug or feature?</p>",
        "id": 153921434,
        "sender_full_name": "Timo Aaltonen",
        "timestamp": 1511517591
    },
    {
        "content": "<p>Might be due to your client configuration, if you pm me the client id we'll check it! Or if you want to reconfigure it yourself check that it has \"offline_access\" scope and \"refresh tokens are granted\" checkbox  is set.</p>\n<p>Edited to add: if it uses the professional grant type and not the authorization grant flow, then it is feature and as it should be.</p>",
        "id": 153921789,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1511862356
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"192813\">@Eeva Turkka</span> <span class=\"user-mention\" data-user-id=\"194314\">@Timo Aaltonen</span>  I just noticed the same. Before, I got the token with \"openid\" \"profile\" \"offline_access\" all set, and was able to refresh that token too. I then added some other scopes, and fetched a new token. Now the authorization process seems to ignore those scopes, and always returns a token without any of them.</p>",
        "id": 153922083,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1511970965
    },
    {
        "content": "<p>Also, I wasn't able to get StructureDefinition.read / StructureDefinition.write scopes for the app, although I did add them to the client definition in the auth server, and also to the auth request.</p>",
        "id": 153922084,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1511971077
    },
    {
        "content": "<p>Did you list all of the scopes together including the offline_access from before when you added more scopes? Our regression set keeps getting refreshed tokens so I need a bit more info to figure this one out :)</p>",
        "id": 153922148,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1511986271
    },
    {
        "content": "<p>Yes. Before the change the app was specified as having scopes \"patient/MedicationAdministration.write patient/MedicationAdministration.read openid offline_access profile patient/Observation.read patient/Observation.write\" and the auth request requested for \"openid profile patient/Observation.read patient/Observation.write patient/MedicationAdministration.read patient/MedicationAdministration.write offline_access\".</p>",
        "id": 153922150,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1511986505
    },
    {
        "content": "<p>It used to work, but does not anymore. Even with that same configuration, the authorization process only yields the limited scope to the token.</p>",
        "id": 153922151,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1511986553
    },
    {
        "content": "<p>We'll try to reproduce this and if we cannot we'll ask for more details! (<span class=\"user-mention\" data-user-id=\"197084\">@Matti Uusitalo</span>  pinging you in case I forget to mention this tomorrow morning)</p>",
        "id": 153922153,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1511986778
    },
    {
        "content": "<p>We've managed to reproduce this, this is cause by a bug that doesn't authorize citizen-clients to use those scopes (but if they were authorized, they remain so, so new authorization request removes them.). This is not intended and will be fixed in next update!</p>",
        "id": 153922238,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1512026909
    },
    {
        "content": "<p>Has there been any changes in the authorization? It used to work in October when I last checked it. Now I am getting {\"error\":\"unauthorized\",\"error_description\":\"No AuthenticationProvider found for fi.kela.kanta.phr.auth.token.PhrOidAuthenticationToken\"} when executing the 2nd phase i.e. <a href=\"https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/token\" target=\"_blank\" title=\"https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/token\">https://fhirsandbox2-auth.kanta.fi/phr-authserver-sandbox/token</a>.</p>",
        "id": 153923667,
        "sender_full_name": "Juha Leppänen",
        "timestamp": 1512720748
    },
    {
        "content": "<p>I confirm this is now working, and I get 'openid', 'profile', and 'access_token' scopes as expected.</p>",
        "id": 153923673,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1512724209
    },
    {
        "content": "<p>I don't get scopes for reading and writing StructureDefinitions, though. So I assume I can't do that programmatically, rather I must use the user interface of the non-authenticating sandbox.</p>",
        "id": 153923674,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1512724281
    },
    {
        "content": "<p>(meant to say the issue with scopes is working, not to comment on PhrOidAuthenticationToken)</p>",
        "id": 153923675,
        "sender_full_name": "Mikael Rinnetmäki",
        "timestamp": 1512724336
    },
    {
        "content": "<p>This looks very much like an issue we need to check! I've asked our testing to check if they can reproduce this, but if not I'll ask for more details.</p>",
        "id": 153924231,
        "sender_full_name": "Eeva Turkka",
        "timestamp": 1512996431
    }
]