---
layout: page
title: "FHIR Chat  · HibernateException · implementers"
---

{% raw %}<h2>Stream: <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/index.html">implementers</a></h2>
<h3>Topic: <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html">HibernateException</a></h3>

<hr>

<base href="https://chat.fhir.org">

<head><link href="https://fhir.github.io/chat-archive/style.css" rel="stylesheet"></head>

<a name="153903744"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/153903744" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jake Hardy <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#153903744">(Aug 25 2017 at 15:28)</a>:</h4>
<p>Good morning everybody. I've been doing some validation against the HAPI server, and I keep getting multiple instances of this exception: </p>
<p>"Error org.hibernate.HibernateException: Unable to access lob stream; nested exception is javax.persistence.PersistenceException: org.hibernate.HibernateException: Unable to access lob stream validating {someElement}"</p>
<p>The strange thing is that sometimes it comes back as a warning, while other times coming back as an error. Does anybody know what this error means, or have any insight on how to fix it?</p>



<a name="153903747"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/153903747" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Lloyd McKenzie <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#153903747">(Aug 25 2017 at 15:59)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> ?</p>



<a name="234372705"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234372705" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234372705">(Apr 13 2021 at 17:57)</a>:</h4>
<p>I am experiencing the same problem running 5.3 in docker, <span class="user-mention" data-user-id="191319">@James Agnew</span>  any nudges to help proceed forward ?</p>



<a name="234373244"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373244" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373244">(Apr 13 2021 at 18:00)</a>:</h4>
<p>are you able to reproduce this on <a href="http://hapi.fhir.org">hapi.fhir.org</a>?</p>



<a name="234373419"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373419" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373419">(Apr 13 2021 at 18:01)</a>:</h4>
<p><span class="user-mention silent" data-user-id="191319">James Agnew</span> <a href="#narrow/stream/179166-implementers/topic/HibernateException/near/234373244">said</a>:</p>
<blockquote>
<p>are you able to reproduce this on <a href="http://hapi.fhir.org">hapi.fhir.org</a>?</p>
</blockquote>
<p>How would I do that? I am running 5.3.0 in Docker and I see this in my logs</p>
<div class="codehilite"><pre><span></span><code>Hibernate:
    select
        resourcehi0_.pid as pid1_12_0_,
        resourcehi1_.res_ver_pid as res_ver_1_13_1_,
        resourcehi0_.partition_date as partitio2_12_0_,
        resourcehi0_.partition_id as partitio3_12_0_,
        resourcehi0_.res_deleted_at as res_dele4_12_0_,
        resourcehi0_.res_version as res_vers5_12_0_,
        resourcehi0_.has_tags as has_tags6_12_0_,
        resourcehi0_.res_published as res_publ7_12_0_,
        resourcehi0_.res_updated as res_upda8_12_0_,
        resourcehi0_.res_encoding as res_enco9_12_0_,
        resourcehi0_.res_text as res_tex10_12_0_,
        resourcehi0_.res_id as res_id11_12_0_,
        resourcehi0_.res_type as res_typ12_12_0_,
        resourcehi0_.res_ver as res_ver13_12_0_,
        resourcehi1_.partition_date as partitio2_13_1_,
        resourcehi1_.partition_id as partitio3_13_1_,
        resourcehi1_.request_id as request_4_13_1_,
        resourcehi1_.res_pid as res_pid6_13_1_,
        resourcehi1_.source_uri as source_u5_13_1_
    from
        hfj_res_ver resourcehi0_
    left outer join
        hfj_res_ver_prov resourcehi1_
            on resourcehi0_.pid=resourcehi1_.res_ver_pid
    where
        resourcehi0_.res_id=?
        and resourcehi0_.res_ver=?
2021-04-13 18:01:14.822 [main] ERROR c.u.f.jpa.searchparam.retry.Retrier [Retrier.java:79] Retry failure 31/60: org.springframework.orm.jpa.JpaSystemException: Unable to access lob stream; nested exception is org.hibernate.HibernateException: Unable to access lob stream
</code></pre></div>



<a name="234373570"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373570" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373570">(Apr 13 2021 at 18:02)</a>:</h4>
<p>like, can you upload any data you'd need in order to simulate the same scenario on <a href="http://hapi.fhir.org">hapi.fhir.org</a>, and share a link that shows it?</p>



<a name="234373688"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373688" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373688">(Apr 13 2021 at 18:03)</a>:</h4>
<p><span class="user-mention silent" data-user-id="191319">James Agnew</span> <a href="#narrow/stream/179166-implementers/topic/HibernateException/near/234373570">said</a>:</p>
<blockquote>
<p>like, can you upload any data you'd need in order to simulate the same scenario on <a href="http://hapi.fhir.org">hapi.fhir.org</a>, and share a link that shows it?</p>
</blockquote>
<p>no this is happening on Server start it self .... I haven't even accessed the UI yet</p>



<a name="234373788"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373788" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373788">(Apr 13 2021 at 18:04)</a>:</h4>
<p>again this may be bcoz of <code>hapiproject/hapi:latest</code> which was built off of master branch, running on DB schema migrated by 5.3.0 CLI</p>



<a name="234373823"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373823" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373823">(Apr 13 2021 at 18:04)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span>  ^</p>



<a name="234373887"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373887" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373887">(Apr 13 2021 at 18:05)</a>:</h4>
<p>hmm, not sure unfortunately. i don't know a lot about the docker build</p>



<a name="234373947"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373947" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373947">(Apr 13 2021 at 18:05)</a>:</h4>
<p>does this happen if you don't use the docker build?</p>



<a name="234373987"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234373987" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234373987">(Apr 13 2021 at 18:05)</a>:</h4>
<p>do I need to enable the logger in <code>application.yml</code> for this error to go away ? currently its commented out</p>



<a name="234374348"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234374348" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234374348">(Apr 13 2021 at 18:08)</a>:</h4>
<p>not sure, does that solve the issue?</p>



<a name="234375081"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234375081" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234375081">(Apr 13 2021 at 18:13)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span>  no it does not</p>



<a name="234379541"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234379541" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234379541">(Apr 13 2021 at 18:43)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> some more insights here. This issue was reported here <a href="https://github.com/hapifhir/hapi-fhir/issues/2034">https://github.com/hapifhir/hapi-fhir/issues/2034</a> <br>
I am  trying to run JPA  5.3.0 from dockerhub <code>hapiproject/hapi</code> the server won't start unless I can get past that exception</p>



<a name="234380252"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234380252" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> James Agnew <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234380252">(Apr 13 2021 at 18:48)</a>:</h4>
<p>Well, FWIW that issue was fixed so I assume it's not exactly that (or it's the same thing happening elsewhere). If you are able to reproduce it outside of docker, please feel free to file a bug with the steps to reproduce, any stack trace, etc</p>



<a name="234416327"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234416327" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234416327">(Apr 13 2021 at 23:15)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> on 5.3.0 on Debian (buster) with Java 11.0.8, I still get the same error regardless if the WAR is run outside or inside docker</p>
<p><strong>The JPA Server does not start</strong></p>
<p>I am using PostGresql 12.5</p>



<a name="234417268"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234417268" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234417268">(Apr 13 2021 at 23:25)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> seems like this may be a problem emanating from the DB schema migration by <code>hapi-fhir-cli</code> <a href="https://stackoverflow.com/questions/38511205/org-hibernate-hibernateexception-org-postgresql-util-psqlexception-large-objec">https://stackoverflow.com/questions/38511205/org-hibernate-hibernateexception-org-postgresql-util-psqlexception-large-objec</a></p>



<a name="234419227"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234419227" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234419227">(Apr 13 2021 at 23:44)</a>:</h4>
<p><span class="user-mention" data-user-id="191319">@James Agnew</span> I even tried to change the Hibernate DDL properties <code>hibernate.hbm2ddl.auto: create-drop</code> and I still get the same error</p>
<div class="codehilite"><pre><span></span><code>2021-04-13 23:40:57.842 [main] ERROR c.u.f.jpa.searchparam.retry.Retrier [Retrier.java:79] Retry failure 4/60: org.springframework.orm.jpa.JpaSystemException: Unable to access lob stream; nested exception is org.hibernate.HibernateException: Unable to access lob stream
````
</code></pre></div>



<a name="234419240"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234419240" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234419240">(Apr 13 2021 at 23:44)</a>:</h4>
<p><span class="user-mention" data-user-id="379920">@Ken Stevens</span> any idea ?</p>



<a name="234454941"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179166-implementers/topic/HibernateException/near/234454941" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> dsh <a href="https://fhir.github.io/chat-archive/stream/179166-implementers/topic/HibernateException.html#234454941">(Apr 14 2021 at 07:41)</a>:</h4>
<p>Finally I got past that error by running this PLSQL function on Large Objects in my Postgres 12.6 on AWS RDS</p>
<div class="codehilite"><pre><span></span><code>CREATE OR REPLACE FUNCTION public.grant_select_on_large_objects()
 RETURNS text
 LANGUAGE plpgsql
AS $function$

    DECLARE
        REC BIGINT;

    begin

        FOR REC in   SELECT OID FROM pg_catalog.pg_largeobject_metadata
        loop

            execute &#39;grant select on LARGE OBJECT &#39; || REC || &#39; to caringly_db_master&#39;;

--          select &#39;LOBID is &#39; || REC.oid;

        END LOOP;

        return &#39;DONE&#39;;
    END;
$function$
;
</code></pre></div>


{% endraw %}
<hr><p>Last updated: Apr 12 2022 at 19:14 UTC</p>
