[
    {
        "content": "<p>Hello all,<br>\nI am getting this Exception from time to time in my program:</p>\n<p>File \"C:\\Users\\Sartori\\Documents\\ADT\\sapadt_to_fhir\\segments\\patient_identification.py\", line 195, in post_process<br>\n    self.patient_json = self.patient_object.as_json()<br>\n  File \"C:\\Users\\Sartori\\AppData\\Roaming\\Python\\Python38\\site-packages\\fhirclient\\models\\fhirabstractresource.py\", line 42, in as_json<br>\n    js = super(FHIRAbstractResource, self).as_json()<br>\n  File \"C:\\Users\\Sartori\\AppData\\Roaming\\Python\\Python38\\site-packages\\fhirclient\\models\\fhirabstractbase.py\", line 297, in as_json<br>\n    raise FHIRValidationError(errs)<br>\nfhirclient.models.fhirabstractbase.FHIRValidationError: {root}:<br>\n  contact.0:<br>\n    name:<br>\n      given:<br>\n        Expecting property \"given\" on &lt;class 'fhirclient.models.humanname.HumanName'&gt; to be &lt;class 'str'&gt;, but is &lt;class 'list'&gt;</p>\n<p>Is this a bug? \"Given\" in Humanname clearly supposed to be a list according to documentation <a href=\"https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/78879\">https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/78879</a>. The strangest thing is that I only get this exception from time to time (like 1/1000 patient ressources created).</p>\n<p>My code builds the name like this:</p>\n<p>name_obj = humanname.HumanName()<br>\n<a href=\"http://name_obj.family\">name_obj.family</a> = family<br>\nname_obj.given = [given] if given else None<br>\nname_obj.use = \"official\"<br>\n name_obj.suffix = [suffix] if suffix else None</p>",
        "id": 240130725,
        "sender_full_name": "Alice Sartori Monteiro de Barros",
        "timestamp": 1621903170
    },
    {
        "content": "<p>HumanName.given is a list of strings. I think your code works as long as the given variable here is a string because you're already assigning it inside a list. But if your source patient data has multiple given names already in a list, this will probably cause this error because then you're putting a list inside a list.</p>",
        "id": 240177716,
        "sender_full_name": "Julian Sass",
        "timestamp": 1621945007
    },
    {
        "content": "<h1>here is what <span class=\"user-mention\" data-user-id=\"194952\">@Julian Sass</span>  is talking about...</h1>\n<div class=\"codehilite\" data-code-language=\"Python\"><pre><span></span><code><span class=\"kn\">from</span>  <span class=\"nn\">fhirclient.r4models</span> <span class=\"kn\">import</span> <span class=\"n\">humanname</span>\n<span class=\"kn\">from</span> <span class=\"nn\">json</span> <span class=\"kn\">import</span> <span class=\"n\">dumps</span><span class=\"p\">,</span> <span class=\"n\">loads</span><span class=\"p\">,</span> <span class=\"n\">load</span>\n</code></pre></div>\n<div class=\"codehilite\" data-code-language=\"Python\"><pre><span></span><code><span class=\"n\">given</span> <span class=\"o\">=</span> <span class=\"p\">[</span><span class=\"s1\">'given1'</span><span class=\"p\">,</span><span class=\"s1\">'given2'</span><span class=\"p\">]</span>\n<span class=\"n\">suffix</span> <span class=\"o\">=</span> <span class=\"kc\">None</span>\n\n<span class=\"n\">name_obj</span><span class=\"o\">.</span><span class=\"n\">family</span> <span class=\"o\">=</span> <span class=\"s1\">'family'</span>\n<span class=\"n\">name_obj</span><span class=\"o\">.</span><span class=\"n\">given</span> <span class=\"o\">=</span> <span class=\"p\">[</span><span class=\"n\">given</span><span class=\"p\">]</span> <span class=\"k\">if</span> <span class=\"n\">given</span> <span class=\"k\">else</span> <span class=\"kc\">None</span>\n<span class=\"n\">name_obj</span><span class=\"o\">.</span><span class=\"n\">use</span> <span class=\"o\">=</span> <span class=\"s2\">\"official\"</span>\n<span class=\"n\">name_obj</span><span class=\"o\">.</span><span class=\"n\">suffix</span> <span class=\"o\">=</span> <span class=\"p\">[</span><span class=\"n\">suffix</span><span class=\"p\">]</span> <span class=\"k\">if</span> <span class=\"n\">suffix</span> <span class=\"k\">else</span> <span class=\"kc\">None</span>\n\n<span class=\"n\">name_obj</span><span class=\"o\">.</span><span class=\"n\">as_json</span><span class=\"p\">()</span>\n</code></pre></div>\n<div class=\"codehilite\"><pre><span></span><code>---------------------------------------------------------------------------\n\nFHIRValidationError                       Traceback (most recent call last)\n\n&lt;ipython-input-44-f9172b1b931a&gt; in &lt;module&gt;\n      7 name_obj.suffix = [suffix] if suffix else None\n      8 \n----&gt; 9 name_obj.as_json()\n\n\n~/Documents/Python/Venv/venv37/lib/python3.7/site-packages/fhirclient/r4models/fhirabstractbase.py in as_json(self)\n    295 \n    296         if len(errs) &gt; 0:\n--&gt; 297             raise FHIRValidationError(errs)\n    298         return js\n    299\n\n\nFHIRValidationError: {root}:\n  given:\n    Expecting property &quot;given&quot; on &lt;class &#39;fhirclient.r4models.humanname.HumanName&#39;&gt; to be &lt;class &#39;str&#39;&gt;, but is &lt;class &#39;list&#39;&gt;\n</code></pre></div>",
        "id": 240213520,
        "sender_full_name": "Eric Haas",
        "timestamp": 1621959832
    }
]