[
    {
        "content": "<p>Hi All,  I have below constrain on consent resource - <br>\n&lt;constraint&gt;<br>\n&lt;key value=\"Consent-1\"/&gt;<br>\n&lt;severity value=\"error\"/&gt;<br>\n&lt;human value=\"<a href=\"http://consent.except.actor\">consent.except.actor</a> should be subset of consent.actor\"/&gt;<br>\n&lt;expression value=\"Consent.except.actor.reference.subsetOf(Consent.actor.reference)\"/&gt;<br>\n&lt;/constraint&gt;<br>\nand in sample <a href=\"http://consent.except.actor\">consent.except.actor</a>  list is subset of <a href=\"http://consent.actor\">consent.actor</a> but still sample is failing with mentioned error.<br>\nI am using Validator 5.2.3 and not sure if the subsetOf function is supported by validator or not or I am doing something wrong? <br>\nThanks</p>",
        "id": 224742785,
        "sender_full_name": "Kailash",
        "timestamp": 1612193664
    },
    {
        "content": "<p>I think you probably meant to post this on the \"fhirpath\" stream.  This stream (\"fhirpath.js\") is about the JavaScript implementation of FHIRPath named \"fhirpath.js\".</p>",
        "id": 224768330,
        "sender_full_name": "Paul Lynch",
        "timestamp": 1612203473
    }
]