[
    {
        "content": "<p>It seems a partial build will say Success even when there are errors with examples. Is this a change? <a href=\"/user_uploads/10155/luqd9zCKjb9Kqje4VsMjp0Ni/Build-Screenshot-2021-07-30-215039.png\">Build-Screenshot-2021-07-30-215039.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/luqd9zCKjb9Kqje4VsMjp0Ni/Build-Screenshot-2021-07-30-215039.png\" title=\"Build-Screenshot-2021-07-30-215039.png\"><img src=\"/user_uploads/10155/luqd9zCKjb9Kqje4VsMjp0Ni/Build-Screenshot-2021-07-30-215039.png\"></a></div>",
        "id": 247882158,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1627860233
    },
    {
        "content": "<p>and it seems the full build has same issue <span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span> <br>\n<a href=\"/user_uploads/10155/9_M8vdarNETzjnvhmhKtWYKr/full-build-Screenshot-2021-08-02-105055.png\">full-build-Screenshot-2021-08-02-105055.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/10155/9_M8vdarNETzjnvhmhKtWYKr/full-build-Screenshot-2021-08-02-105055.png\" title=\"full-build-Screenshot-2021-08-02-105055.png\"><img src=\"/user_uploads/10155/9_M8vdarNETzjnvhmhKtWYKr/full-build-Screenshot-2021-08-02-105055.png\"></a></div>",
        "id": 247905079,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1627898016
    },
    {
        "content": "<p>What am I looking at here?</p>",
        "id": 248214892,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1627994478
    },
    {
        "content": "<p>I'm assuming this is a build of the website? What branch is this on? Is this only local? Or does this also happen remotely?</p>",
        "id": 248215006,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1627994531
    },
    {
        "content": "<p>It's a local build of FHIR. It happens locally, and it didn't happen locally until recently. This was an R4B branch. Hard to see how it could be branch related, since the build software itself is behaving differently. Not sure about remotely, because that succeeds. But I am not sure if it succeeds with errors, because it succeeds, so I never went to check.</p>",
        "id": 248224262,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1627999100
    },
    {
        "content": "<p>Can you open a PR for the branch please? We can check the logs on the build server and see what the outcome is.</p>",
        "id": 248227402,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628000470
    },
    {
        "content": "<p>Then, if it's still failing, I can look into it further</p>",
        "id": 248227444,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628000490
    },
    {
        "content": "<p>it would only show on a bad build (incorrect examples) and I have tried to avoid committing those, so there may well not be any on the build server.</p>",
        "id": 248230101,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1628001644
    },
    {
        "content": "<p>So the question you are asking is \"why would the build throw errors, but still succeed?\"</p>",
        "id": 248231041,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628002049
    },
    {
        "content": "<p>Can you copy paste the actual errors as text.</p>",
        "id": 248231192,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628002100
    },
    {
        "content": "<p>So I can look at them in the code</p>",
        "id": 248231208,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628002109
    },
    {
        "content": "<p>Also, are they the same errors every time?</p>",
        "id": 248231218,
        "sender_full_name": "Mark Iantorno",
        "timestamp": 1628002116
    },
    {
        "content": "<p>I suspect Grahame loosened the rules because at one point (and possibly still), the examples were such a mess that failing the build because of them meant the build would be offline for an extended period.  How many examples now fail?</p>",
        "id": 248232508,
        "sender_full_name": "Lloyd McKenzie",
        "timestamp": 1628002649
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"248736\">@Mark Iantorno</span> yes. But its not the errors that are the issue, its the lack of the build catching them. The error message is \"build successful\" ;-)<br>\nAnyway this is one:<br>\nERROR @ Observation (line 0, col0): observation-example-genetics-brcapat:: Observation: Observation.effective[x]: minimum required = 1, but only found 0 (from <a href=\"http://hl7.org/fhir/StructureDefinition/devicemetricobservation\">http://hl7.org/fhir/StructureDefinition/devicemetricobservation</a>) (src = InstanceValidator)</p>\n<p>I have only noticed it on local builds where I am making changes and have broken the examples myself - and the build used to be a good way to find the errors. (It is not usually possible to validate examples outside of the build, because the schemas the build generates are not valid...). But now I look at other examples, there are lots of them.</p>",
        "id": 248234584,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1628003511
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191320\">@Lloyd McKenzie</span> that makes sense. It may be because lots of failures about things like about contained references, which at least at one stage, were not validated correctly. But this may have had the effect of letting more bad examples in if people no longer notice that they fail.</p>",
        "id": 248234654,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1628003526
    },
    {
        "content": "<p>So in summary this is probably not something that needs a direct fix itself (unless maybe a \"strict\" mode?), but is now a mess :-)</p>",
        "id": 248234680,
        "sender_full_name": "Rik Smithies",
        "timestamp": 1628003538
    },
    {
        "content": "<p>R4B examples aren't valid, but I thought R5 fails if they're not. Not necessarily for a partial build though</p>",
        "id": 249674976,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1629170730
    },
    {
        "content": "<p>FWIW, the problem I was running into yesterday (typo in xml ‘value’ for the short description) also only showed up in full builds.  Partial ones reported success.</p>",
        "id": 249710594,
        "sender_full_name": "Gino Canessa",
        "timestamp": 1629203271
    }
]