[
    {
        "content": "<p>when validating an Observation resource against profile <a href=\"https://simplifier.net/NictizSTU3-Zib2017/ZibAlcoholUse/~xml\">https://simplifier.net/NictizSTU3-Zib2017/ZibAlcoholUse/~xml</a> the response contains the following issue: </p>\n<div class=\"codehilite\"><pre><span></span><code>&quot;issue&quot;: [ {\n     &quot;severity&quot;: &quot;error&quot;,\n     &quot;code&quot;: &quot;processing&quot;,\n     &quot;diagnostics&quot;: &quot;Failed to generate snapshot&quot;\n} ]\n</code></pre></div>\n<p>The following info in the logs stood out to me:</p>\n<div class=\"codehilite\"><pre><span></span><code>Caused by: org.hl7.fhir.exceptions.FHIRException:\nAttempt to use a snapshot on profile\n&#39;http://nictiz.nl/fhir/StructureDefinition/zib-Encounter&#39;\nas Base for generating a snapshot for the profile\nhttp://nictiz.nl/fhir/StructureDefinition/gp-Encounter\nbefore it is generated\n</code></pre></div>\n<p>the two profiles in the exception can be found here:</p>\n<ul>\n<li><a href=\"https://simplifier.net/NictizSTU3-Zib2017/gp-Encounter/~xml\">https://simplifier.net/NictizSTU3-Zib2017/gp-Encounter/~xml</a></li>\n<li><a href=\"https://simplifier.net/NictizSTU3-Zib2017/ZibEncounter/~xml\">https://simplifier.net/NictizSTU3-Zib2017/ZibEncounter/~xml</a></li>\n</ul>\n<p>What can I do to resolve this?</p>",
        "id": 217293064,
        "sender_full_name": "Job Schipper",
        "timestamp": 1605802821
    },
    {
        "content": "<p>running into the same problem here so following this</p>",
        "id": 217411410,
        "sender_full_name": "Remco Overdevest",
        "timestamp": 1605884517
    },
    {
        "content": "<p>so first of all, what version of HAPI are you using? I fixed up an issue like this a few months ago</p>",
        "id": 217583144,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1606098153
    },
    {
        "content": "<p>Are you using derived profiles? English pharmacy profiles (which are based on UK profiles), have this issue with 5.2 HAPI. 5.1 works still.</p>",
        "id": 217593492,
        "sender_full_name": "Kevin Mayfield",
        "timestamp": 1606113783
    },
    {
        "content": "<p>Does the validator itself has this problem when run in standalone mode?</p>",
        "id": 217593663,
        "sender_full_name": "Grahame Grieve",
        "timestamp": 1606113993
    },
    {
        "content": "<p>No it's just when using hapi validation</p>",
        "id": 217593926,
        "sender_full_name": "Kevin Mayfield",
        "timestamp": 1606114364
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  In my case it's <code> hapiproject/hapi:v5.1.0</code> from docker hub</p>",
        "id": 217599706,
        "sender_full_name": "Job Schipper",
        "timestamp": 1606120215
    },
    {
        "content": "<p>I managed to import the <code>nictiz.fhir.nl.stu3.zib2017 2.0.0</code> implementation guide package by using the version including snapshots. Now running into the next problem with the package <code>nictiz.fhir.nl.stu3.geboortezorg</code> with the following stacktrace:</p>\n<div class=\"codehilite\"><pre><span></span><code>Caused by: org.hl7.fhir.exceptions.DefinitionException: Attempt to a slice an element that does not repeat: EpisodeOfCare.diagnosis.condition/EpisodeOfCare.diagnosis.condition from http://fhir.nl/fhir/StructureDefinition/nl-core-episodeofcare in , at element EpisodeOfCare.diagnosis.condition (slice = pregnancy)\n    at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1362)\n    at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1025)\n    at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1025)\n    at org.hl7.fhir.r5.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:612)\n    at org.hl7.fhir.common.hapi.validation.support.SnapshotGeneratingValidationSupport.generateSnapshot(SnapshotGeneratingValidationSupport.java:104)\n    ... 96 common frames omitted\n</code></pre></div>",
        "id": 217612812,
        "sender_full_name": "Remco Overdevest",
        "timestamp": 1606128386
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"365684\">@Remco Overdevest</span>  I have had similar errors with other nictiz profiles. I think in those cases the exception is correct, and this  has to be fixed in the profile (StructureDefinition). you can try to report it at <a href=\"https://bits.nictiz.nl/\">https://bits.nictiz.nl/</a></p>",
        "id": 217619297,
        "sender_full_name": "Job Schipper",
        "timestamp": 1606132874
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"365684\">@Remco Overdevest</span>  what do you mean by \"the version including snapshots\"? do you have a link?</p>",
        "id": 217619454,
        "sender_full_name": "Job Schipper",
        "timestamp": 1606132996
    },
    {
        "content": "<p><a href=\"https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.0.3\">https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.0.3</a> top right <code>Download</code> dropdown and click <code>Download snapshots</code>.</p>",
        "id": 217619766,
        "sender_full_name": "Remco Overdevest",
        "timestamp": 1606133213
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"365684\">@Remco Overdevest</span>  i just noticed that, from the stracktrace,  it looks like you're using HL7 FHIR version \"r5\", while the profile <code>nictiz.fhir.nl.stu3.geboortezorg</code> is based on STU3. this might also cause issues?</p>",
        "id": 217632668,
        "sender_full_name": "Job Schipper",
        "timestamp": 1606141156
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"294094\">@Job Schipper</span> I've noticed that as well but after debugging it seems that the r5 classes are always used with a <code>VersionSpecificWorkerContextWrapper</code>.  This class contains the correct FhirContext(DSTU3). Thanks for checking tho.</p>",
        "id": 217637180,
        "sender_full_name": "Remco Overdevest",
        "timestamp": 1606143413
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"191316\">@Grahame Grieve</span>  i'm still experiencing this issue. I previously worked around it by removing this profile, but now I do need it. Can you confirm if the fix you mentioned was before or after v5.1.0 ?</p>",
        "id": 222278276,
        "sender_full_name": "Job Schipper",
        "timestamp": 1610359684
    },
    {
        "content": "<p>FYI, I now managed to import the package that already contains the snapshots as Remco suggested, so I'm no longer depending on the geneation. Hopefully the fix you mentioned was implemented after v5.1.0, if not I can supply more information to reproduce it on that version.</p>",
        "id": 222285688,
        "sender_full_name": "Job Schipper",
        "timestamp": 1610364601
    }
]