---
layout: page
title: "FHIR Chat  · Validator error on urn ValueSets · conformance"
---

{% raw %}<h2>Stream: <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/index.html">conformance</a></h2>
<h3>Topic: <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html">Validator error on urn ValueSets</a></h3>

<hr>

<base href="https://chat.fhir.org">

<head><link href="https://fhir.github.io/chat-archive/style.css" rel="stylesheet"></head>

<a name="175626932"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/175626932" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Noemi Deppenwiese <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#175626932">(Sep 13 2019 at 14:07)</a>:</h4>
<p>In my profile (<a href="https://simplifier.net/bbmri.de/specimen" target="_blank" title="https://simplifier.net/bbmri.de/specimen">https://simplifier.net/bbmri.de/specimen</a> under collection.bodySite.coding) I specified a ValueSet using its urn (got that from ART-DECOR).  Now the validator (in the IG publisher) throws an org.hl7.fhir.exceptions.FHIRException: not done yet: can't fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36 . So, is a ValueSet binding via urn valid? If yes, could this exception be downgraded to a warning so the IG Publisher can run and generate an IG? <br>
Thanks!</p>



<a name="175632568"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/175632568" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Grahame Grieve <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#175632568">(Sep 13 2019 at 15:03)</a>:</h4>
<p>where does it blow up? what's the stack?</p>



<a name="175791366"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/175791366" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Noemi Deppenwiese <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#175791366">(Sep 16 2019 at 08:04)</a>:</h4>
<div class="codehilite"><pre><span></span>Exception in thread &quot;main&quot; java.lang.Error: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36
        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:857)
        at org.hl7.fhir.r5.context.SimpleWorkerContext.fetchResource(SimpleWorkerContext.java:565)
        at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.resolveBinding(IGKnowledgeProvider.java:489)
        at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.resolveBinding(IGKnowledgeProvider.java:424)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateDescription(ProfileUtilities.java:3021)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateDescription(ProfileUtilities.java:2930)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2649)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2711)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.genElement(ProfileUtilities.java:2711)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateTable(ProfileUtilities.java:2504)
        at org.hl7.fhir.igtools.renderers.StructureDefinitionRenderer.snapshot(StructureDefinitionRenderer.java:350)
        at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsStructureDefinition(Publisher.java:5895)
        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:5263)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:3876)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:735)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:612)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:6451)
Caused by: org.hl7.fhir.exceptions.FHIRException: not done yet: can&#39;t fetch urn:oid:1.3.6.1.4.1.19376.1.3.11.36
        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResourceWithException(BaseWorkerContext.java:800)
        at org.hl7.fhir.r5.context.BaseWorkerContext.fetchResource(BaseWorkerContext.java:855)
        ... 16 more
</pre></div>



<a name="175796519"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/175796519" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Grahame Grieve <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#175796519">(Sep 16 2019 at 09:24)</a>:</h4>
<p>you need to include the value set in the IG so that the publisher can find it. It's ok for it to have a urn:  but the error messag reflects that this is not normal behavior (we encourage use of http: urls but it's not mandatory)</p>



<a name="178466000"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178466000" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178466000">(Oct 18 2019 at 11:50)</a>:</h4>
<p>Did you get any feedback on this issue? Seems to be a problem with any unresolvable ValueSet binding. This also shows up in the official validator package when I try to validate this resource:<br>
<a href="https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2" target="_blank" title="https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2">https://simplifier.net/hl7norwayno-basis/relatedperson-example-duplicate-2</a></p>



<a name="178466204"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178466204" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178466204">(Oct 18 2019 at 11:54)</a>:</h4>
<p>A quick follow up on this. How do you make this work when you validate against a directory of Conformance resources? Should you include an XML file with the oid as the filename? Or define a Valuset with the oid as the ValueSet.url?</p>



<a name="178467059"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178467059" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Noemi Deppenwiese <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178467059">(Oct 18 2019 at 12:09)</a>:</h4>
<p>I made it work by using the ArtDecor URL for the ValueSet ("valueSet": "<a href="http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623" target="_blank" title="http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623">http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623</a>") instead of just the URN in the profile... The publisher still complains about not finding a ValueSet there, but it continues the publishing process and and no longer throws an Exception. The output looks good enough and I dindn't encounter any further issues yet. <a href="/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png" target="_blank" title="publisher.png">publisher.png</a></p>
<div class="message_inline_image"><a href="/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png" target="_blank" title="publisher.png"><img src="/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png"></a></div><p>When validating resources (using just the urn as system), the validator only issues a warning and not an error which is good enough for our use case.</p>



<a name="178632140"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178632140" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178632140">(Oct 21 2019 at 07:32)</a>:</h4>
<blockquote>
<p>you need to include the value set in the IG so that the publisher can find it. It's ok for it to have a urn:  but the error messag reflects that this is not normal behavior (we encourage use of http: urls but it's not mandatory)</p>
</blockquote>
<p><span class="user-mention" data-user-id="191316">@Grahame Grieve</span>  Should the validator really stop the validation process when it can't locate a ValueSet definition? I think that is unwanted behaviour.</p>



<a name="178642272"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178642272" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178642272">(Oct 21 2019 at 10:20)</a>:</h4>
<blockquote>
<p>I made it work by using the ArtDecor URL for the ValueSet ("valueSet": "<a href="http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623" target="_blank" title="http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623">http://art-decor.org/fhir/ValueSet/1.3.6.1.4.1.19376.1.3.11.36--20151113191623</a>") instead of just the URN in the profile... The publisher still complains about not finding a ValueSet there, but it continues the publishing process and and no longer throws an Exception. The output looks good enough and I dindn't encounter any further issues yet. <a href="/user_uploads/10155/nynTKpGj8P20G7JeuEiiVwdy/publisher.png" target="_blank" title="publisher.png">publisher.png</a></p>
<p>When validating resources (using just the urn as system), the validator only issues a warning and not an error which is good enough for our use case.</p>
</blockquote>
<p>Thank you for the quick update <span class="user-mention" data-user-id="221444">@Noemi Deppenwiese</span> </p>
<p>I can confirm this is working in my profiles as well. But I don't think this is the "right" solution. The spec is quite clear that a ValueSet binding using a oid value should be possible (urn:oid:, and in Norway we want to use this method for legacy ValueSets/CodeSystems that don't have any FHIR representation yet. The validator behaviour makes this more of an issue than necessary in my opinion.</p>



<a name="178683576"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178683576" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Grahame Grieve <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178683576">(Oct 21 2019 at 18:26)</a>:</h4>
<p>ok, I'm home, and catching up. How are you invoking the validator? </p>
<blockquote>
<p>How do you make this work when you validate against a directory of Conformance resources? Should you include an XML file with the oid as the filename? Or define a Valuset with the oid as the ValueSet.url?</p>
</blockquote>
<p>The second. the filename doesn't matter - it will just load all the files it sees and see the value set. The fact that it's using a urn:oid: should be irrelevant, as long as you tell the validator to load it from somewhere</p>



<a name="178730477"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178730477" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178730477">(Oct 22 2019 at 07:39)</a>:</h4>
<p>Thanks for your feedback.</p>
<blockquote>
<p>ok, I'm home, and catching up. How are you invoking the validator? </p>
<p>The second. the filename doesn't matter - it will just load all the files it sees and see the value set. The fact that it's using a urn:oid: should be irrelevant, as long as you tell the validator to load it from somewhere</p>
</blockquote>
<p>I use command line like this:</p>
<div class="codehilite"><pre><span></span>java -jar /home/thomas/Downloads/org.hl7.fhir.validator.jar no-basis-Practitioner-example.xml -ig /media/sf_GitRepo/for-validation -version 4.0.0
</pre></div>


<p>the -ig value points at a catalog containing all my StructureDefinitions, also tried to indlude ValueSet/CodeSystem definition for the oid identified ValuSets/CodeSystems, but the validator still can't identify them and crashes with the "not done yet: can't fetch urn:oid:xxx" error message.</p>
<p>It actually validates the SD's OK, but only until I try to validate the actual examples, then it seems to crash when resolving the ValueSet defined in the Profile.</p>
<p>This is the profile in question:<br>
<a href="https://simplifier.net/hl7norwayno-basis/nobasispractitioner" target="_blank" title="https://simplifier.net/hl7norwayno-basis/nobasispractitioner">https://simplifier.net/hl7norwayno-basis/nobasispractitioner</a></p>
<p>And the example: <br>
<a href="https://simplifier.net/hl7norwayno-basis/practitioner-example" target="_blank" title="https://simplifier.net/hl7norwayno-basis/practitioner-example">https://simplifier.net/hl7norwayno-basis/practitioner-example</a></p>
<p>It only crashes on the last qualification part, because this is the only part where I remembered to add an actual binding of the value coding (have to fix that in the profile): <br>
&lt;qualification&gt;<br>
        &lt;code&gt;<br>
            &lt;coding&gt;<br>
                &lt;system value="urn:oid:2.16.578.1.12.4.1.1.7426" /&gt;<br>
                &lt;code value="152" /&gt;<br>
                &lt;display value="Ortopedisk kirurgi" /&gt;<br>
            &lt;/coding&gt;<br>
        &lt;/code&gt;<br>
    &lt;/qualification&gt;</p>



<a name="178735782"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178735782" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178735782">(Oct 22 2019 at 08:59)</a>:</h4>
<p><span class="user-mention" data-user-id="191316">@Grahame Grieve</span> <br>
Turns out i did at least one mistake on my own. </p>
<p>I used the same url value for my CodeSystem and ValueSet. When I introduced a ValueSet definition using the url: urn:oid:2.16.578.1.12.4.1.1.7426<br>
And identified the CodeSystem using: urn:oid:2.16.578.1.12.4.1.1.7426.codesystem</p>
<p>The validation still fails (my mock up CodeSystem does not actually define any codes yet) but the CodeSystem and ValueSet is resolved correctly by the validator, and the validator don't crash.</p>



<a name="178737473"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178737473" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Grahame Grieve <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178737473">(Oct 22 2019 at 09:25)</a>:</h4>
<p>Oh good!</p>



<a name="178742218"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178742218" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178742218">(Oct 22 2019 at 10:34)</a>:</h4>
<blockquote>
<p>Oh good!</p>
</blockquote>
<p>Well, actually that did not fix it completely.</p>
<p>I got this error that I expected, but the information bit turned out to be quite important:</p>
<div class="codehilite"><pre><span></span>*FAILURE* validating no-basis-Practitioner-example.xml:  error:1 warn:0 info:1
  Error @ Practitioner.qualification[2].code.coding[0] (line 64, col12) : Unknown Code urn:oid:2.16.578.1.12.4.1.1.7426.codesystem#152 in urn:oid:2.16.578.1.12.4.1.1.7426.codesystem for &#39;urn:oid:2.16.578.1.12.4.1.1.7426.codesystem#152&#39;
  Information @ Practitioner.qualification[2].code (line 63, col9) : This element does not match any known slice for the profile http://hl7.no/fhir/StructureDefinition/no-basis-Practitioner
</pre></div>


<p>The validator seems to find the CodeSystem where I now defined the code I am using. But It does not actually manage to find the ValueSet defined by urn:oid:xxx.</p>
<p>The last change I made did  I did not  have a match for the slicing in the profile, because I did not remember to change the fixed string in the slice definition to match my new CodeSystem  url. When I fixed that one, the validator (again) tries to resolve the ValueSet binding in no-basis-Practitioner and crashes. The crash occurs even if I have defined the ValueSet in a file and put the file in the "for-validation" catalog just like the CodeSystem definition. (Now remembering to define different url's for the CodeSystem and the ValueSet).</p>
<p>So there appears to be a problem when the validator tries to resolve ValueSet bindings identified by urn:oid:xxx</p>



<a name="178748381"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/178748381" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#178748381">(Oct 22 2019 at 12:04)</a>:</h4>
<p>If I rename the valueset to something like this (like <span class="user-mention" data-user-id="221444">@Noemi Deppenwiese</span> did in her profiles) it all works out. The Validator finds both the ValueSet and the CodeSystem I have defined in the for-validation catalog, and validates the code defined in CodeSystem.</p>



<a name="179000206"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/179000206" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Grahame Grieve <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#179000206">(Oct 24 2019 at 21:34)</a>:</h4>
<p>so I can't reproduce this - can you package up a folder containing all the relevant resources so I can make sure I have what you have to reproduce the problem?</p>



<a name="179023500"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179177-conformance/topic/Validator%20error%20on%20urn%20ValueSets/near/179023500" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thomas Tveit Rosenlund <a href="https://fhir.github.io/chat-archive/stream/179177-conformance/topic/Validator.20error.20on.20urn.20ValueSets.html#179023500">(Oct 25 2019 at 05:40)</a>:</h4>
<blockquote>
<p>so I can't reproduce this - can you package up a folder containing all the relevant resources so I can make sure I have what you have to reproduce the problem?</p>
</blockquote>
<p>Shure, i will send you a link for download.</p>


{% endraw %}
<hr><p>Last updated: Apr 12 2022 at 19:14 UTC</p>
