---
layout: page
title: "FHIR Chat  · hapi client validate throws exception · hapi"
---

{% raw %}<h2>Stream: <a href="https://fhir.github.io/chat-archive/stream/179167-hapi/index.html">hapi</a></h2>
<h3>Topic: <a href="https://fhir.github.io/chat-archive/stream/179167-hapi/topic/hapi.20client.20validate.20throws.20exception.html">hapi client validate throws exception</a></h3>

<hr>

<base href="https://chat.fhir.org">

<head><link href="https://fhir.github.io/chat-archive/style.css" rel="stylesheet"></head>

<a name="208085166"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179167-hapi/topic/hapi%20client%20validate%20throws%20exception/near/208085166" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Patrick Werner <a href="https://fhir.github.io/chat-archive/stream/179167-hapi/topic/hapi.20client.20validate.20throws.20exception.html#208085166">(Aug 26 2020 at 12:36)</a>:</h4>
<p>When using: <code>client.validate().resource(resource).execute();</code> hapi immediately throws a PrecondotionFailedException<code>Exception in thread "main" ca.uhn.fhir.rest.server.exceptions.PreconditionFailedException: HTTP 412 Precondition Failed: dom-6: A resource should have narrative for robust management [text.div.exists()]</code></p>



<a name="208085266"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179167-hapi/topic/hapi%20client%20validate%20throws%20exception/near/208085266" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Patrick Werner <a href="https://fhir.github.io/chat-archive/stream/179167-hapi/topic/hapi.20client.20validate.20throws.20exception.html#208085266">(Aug 26 2020 at 12:38)</a>:</h4>
<p>The first issue is always thrown as a PrecondotionFailedException, even if it is just a warning</p>



<a name="241785350"></a>
<h4><a href="https://chat.fhir.org#narrow/stream/179167-hapi/topic/hapi%20client%20validate%20throws%20exception/near/241785350" class="zl"><img src="https://fhir.github.io/chat-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Patrick Werner <a href="https://fhir.github.io/chat-archive/stream/179167-hapi/topic/hapi.20client.20validate.20throws.20exception.html#241785350">(Jun 07 2021 at 14:33)</a>:</h4>
<p>I think this is still an issue.</p>


{% endraw %}
<hr><p>Last updated: Apr 12 2022 at 19:14 UTC</p>
